# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gall', '0006_activation_coupon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ambassador',
            name='modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
